---
abstract: 'DBIx::NoSQL as a Moose object store '
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-NoSQL-Store-Manager
provides:
  DBIx::NoSQL::Store::Manager:
    file: lib/DBIx/NoSQL/Store/Manager.pm
    version: v0.2.1
  DBIx::NoSQL::Store::Manager::Model:
    file: lib/DBIx/NoSQL/Store/Manager/Model.pm
    version: v0.2.1
  DBIx::NoSQL::Store::Manager::StoreIndex:
    file: lib/DBIx/NoSQL/Store/Manager/StoreIndex.pm
    version: v0.2.1
  DBIx::NoSQL::Store::Manager::StoreKey:
    file: lib/DBIx/NoSQL/Store/Manager/StoreKey.pm
    version: v0.2.1
requires:
  DBIx::NoSQL::Store: 0
  Method::Signatures: 0
  Module::Pluggable: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::ClassAttribute: 0
  MooseX::Storage: 0.31
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DBIx-NoSQL-Store-Manager
  homepage: http://search.cpan.org/dist/DBIx-NoSQL-Store-Manager/
  repository: https://github.com/yanick/DBIx-NoSQL-Store-Manager.git
version: 0.2.1
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
